import UIProvider from "@/components/providers/UIProvider";
import "@/styles/globals.css";
import { ColorScheme } from "@mantine/core";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "One Connect - Home",
	description: "Generated by One connect",
};

async function getTheme() {
	const cookieStore = cookies();
	const theme = cookieStore.get("scheme-mode");
	return theme;
}

const RootLayout = async ({ children }: { children: ReactNode }) => {
	const data = await getTheme();
	const dataTheme = data?.value as ColorScheme;

	return (
		<html lang="en">
			<body className={inter.className}>
				<UIProvider theme={dataTheme}>{children}</UIProvider>
			</body>
		</html>
	);
};

export default RootLayout;
